micronaut:
  application:
    name: studentcrud

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: admin
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
          show_sql: true